<?php

namespace App\Http\Controllers\Admin\F1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class ContactController extends Controller
{
    // table identity
    public $tableName = 'f1_contact';
    public $primaryKey = 'kid';

    // parameter for select data
    public $select = 'kid, kkode, knama, kkategori, kkategorinama, kcabang, kcabangnama, klokasi, klokasinama, kgudang, kgudangnama, kkategorisalesman, kkategorisalesmannama, karea, kareanama, kkategoricustomer, kkategoricustomernama, kkategorisupplier, kkategorisuppliernama, kdivisi, kdivisinama, ksubdivisi, ksubdivisinama, ksalesman, ksalesmannama, kkontakperson, kterminglobal, kaktif, kaktiftgl, k1alamat1, k1alamat2, k1alamat3, k1alamat4, k1alamat5, k1kota, k1propinsi, k1kodepos, k1negara, k1kontakperson, k1kontaknohp, k1kontakemail, k1notelp1, k1notelp2, k1nofax, k1email, k1website, k2alamat1, k2alamat2, k2alamat3, k2alamat4, k2alamat5, k2propinsi, k2kota, k2kodepos, k2negara, k2kontakperson, k2kontaknohp, k2kontakemail, k2notelp1, k2notelp2, k2nofax, k2email, k2website, k3alamat1, k3alamat2, k3alamat3, k3alamat4, k3alamat5, k3kota, k3propinsi, k3kodepos, k3negara, k3kontakperson, k3kontaknohp, k3kontakemail, k3notelp1, k3notelp2, k3nofax, k3email, k3website, k4alamat1, k4alamat2, k4alamat3, k4alamat4, k4alamat5, k4kota, k4propinsi, k4kodepos, k4negara, k4kontakperson, k4kontaknohp, k4kontakemail, k4notelp1, k4notelp2, k4nofax, k4email, k4website, knpwp, kpkp, kbatashutang, kterminbeli, krekhutang, kbagpembelian, kfobbeli, kviabeli, kbataspiutang, kterminjual, krekpiutang, kbagpenjualan, ktingkatjual, kfobjual, kviajual, ktglkontrak, kbank, knorekening, kjeniskelamin, kmatauang, ktgllahir, ktglnikah, kkomisikode, kkomisipenjualan, kcatatan, kinputuser, kinputtgl, kmodifikasiuser, kmodifikasitgl, ksinkron, kdownloaded, khargacustom, kpajakcustom, ktotalpiutang, ktotalhutang';
    public $selectFormatDate = 'kaktiftgl, ktglkontrak, ktgllahir, ktglnikah, kinputtgl, kmodifikasitgl, kcustomdate1, kcustomdate2, kcustomdate3';

    // Parameter for post data
    public $validatorPost = [
           'kid'   => 'required|numeric|max:20',
           'kkode'   => 'required|max:25',
           'knama'   => 'required|max:100',
           'kkategori'   => 'required|max:20',
           'kkategorinama'   => 'max:50',
           'kcabang'   => 'max:25',
           'kcabangnama'   => 'max:100',
           'klokasi'   => 'max:25',
           'klokasinama'   => 'max:100',
           'kgudang'   => 'max:25',
           'kgudangnama'   => 'max:100',
           'kkategorisalesman'   => 'max:25',
           'kkategorisalesmannama'   => 'max:100',
           'karea'   => 'max:25',
           'kareanama'   => 'max:100',
           'kkategoricustomer'   => 'max:25',
           'kkategoricustomernama'   => 'max:100',
           'kkategorisupplier'   => 'max:25',
           'kkategorisuppliernama'   => 'max:100',
           'kdivisi'   => 'max:25',
           'kdivisinama'   => 'max:100',
           'ksubdivisi'   => 'max:25',
           'ksubdivisinama'   => 'max:100',
           'ksalesman'   => 'numeric|max:20',
           'ksalesmannama'   => 'max:100',
           'kkontakperson'   => 'max:100',
           'kterminglobal'   => 'numeric|max:4',
           'kaktif'   => 'required|numeric|max:2',
           'kaktiftgl'   => 'required|date',
           'k1alamat1'   => 'max:250',
           'k1alamat2'   => 'max:250',
           'k1alamat3'   => 'max:250',
           'k1alamat4'   => 'max:250',
           'k1alamat5'   => 'max:250',
           'k1kota'   => 'max:50',
           'k1propinsi'   => 'max:50',
           'k1kodepos'   => 'max:50',
           'k1negara'   => 'max:50',
           'k1kontakperson'   => 'max:100',
           'k1kontaknohp'   => 'max:50',
           'k1kontakemail'   => 'max:50',
           'k1notelp1'   => 'max:50',
           'k1notelp2'   => 'max:50',
           'k1nofax'   => 'max:50',
           'k1email'   => 'max:50',
           'k1website'   => 'max:50',
           'k2alamat1'   => 'max:250',
           'k2alamat2'   => 'max:250',
           'k2alamat3'   => 'max:250',
           'k2alamat4'   => 'max:250',
           'k2alamat5'   => 'max:250',
           'k2propinsi'   => 'max:50',
           'k2kota'   => 'max:50',
           'k2kodepos'   => 'max:50',
           'k2negara'   => 'max:50',
           'k2kontakperson'   => 'max:100',
           'k2kontaknohp'   => 'max:50',
           'k2kontakemail'   => 'max:50',
           'k2notelp1'   => 'max:50',
           'k2notelp2'   => 'max:50',
           'k2nofax'   => 'max:50',
           'k2email'   => 'max:50',
           'k2website'   => 'max:50',
           'k3alamat1'   => 'max:250',
           'k3alamat2'   => 'max:250',
           'k3alamat3'   => 'max:250',
           'k3alamat4'   => 'max:250',
           'k3alamat5'   => 'max:250',
           'k3kota'   => 'max:50',
           'k3propinsi'   => 'max:50',
           'k3kodepos'   => 'max:50',
           'k3negara'   => 'max:50',
           'k3kontakperson'   => 'max:100',
           'k3kontaknohp'   => 'max:50',
           'k3kontakemail'   => 'max:50',
           'k3notelp1'   => 'max:50',
           'k3notelp2'   => 'max:50',
           'k3nofax'   => 'max:50',
           'k3email'   => 'max:50',
           'k3website'   => 'max:50',
           'k4alamat1'   => 'max:250',
           'k4alamat2'   => 'max:250',
           'k4alamat3'   => 'max:250',
           'k4alamat4'   => 'max:250',
           'k4alamat5'   => 'max:250',
           'k4kota'   => 'max:50',
           'k4propinsi'   => 'max:50',
           'k4kodepos'   => 'max:50',
           'k4negara'   => 'max:50',
           'k4kontakperson'   => 'max:100',
           'k4kontaknohp'   => 'max:50',
           'k4kontakemail'   => 'max:50',
           'k4notelp1'   => 'max:50',
           'k4notelp2'   => 'max:50',
           'k4nofax'   => 'max:50',
           'k4email'   => 'max:50',
           'k4website'   => 'max:50',
           'knpwp'   => 'max:50',
           'kpkp'   => 'numeric|max:2 unsigned',
           'kbatashutang'   => 'numeric',
           'kterminbeli'   => 'max:25',
           'krekhutang'   => 'max:25',
           'kbagpembelian'   => 'numeric|max:20',
           'kfobbeli'   => 'max:25',
           'kviabeli'   => 'max:25',
           'kbataspiutang'   => 'numeric',
           'kterminjual'   => 'max:25',
           'krekpiutang'   => 'max:25',
           'kbagpenjualan'   => 'numeric|max:20 unsigned',
           'ktingkatjual'   => 'numeric|max:11 unsigned',
           'kfobjual'   => 'max:25',
           'kviajual'   => 'max:25',
           'ktglkontrak'   => 'date',
           'kbank'   => 'max:250',
           'knorekening'   => 'max:250',
           'kjeniskelamin'   => 'numeric|max:2 unsigned',
           'kmatauang'   => 'max:10',
           'ktgllahir'   => 'date',
           'ktglnikah'   => 'date',
           'kkomisikode'   => 'max:25',
           'kkomisipenjualan'   => 'numeric',
           'kcatatan'   => 'max:255',
           'kinputuser'   => 'required|numeric|max:20 unsigned',
           'kinputtgl'   => 'required|date',
           'kcustomtext1'   => 'max:250',
           'kcustomtext2'   => 'max:250',
           'kcustomtext3'   => 'max:250',
           'kcustomtext4'   => 'max:250',
           'kcustomtext5'   => 'max:250',
           'kcustomtext6'   => 'max:250',
           'kcustomtext7'   => 'max:250',
           'kcustomtext8'   => 'max:250',
           'kcustomtext9'   => 'max:250',
           'kcustomtext10'   => 'max:250',
           'kcustomint1'   => 'required|numeric|max:11',
           'kcustomint2'   => 'required|numeric|max:11',
           'kcustomint3'   => 'required|numeric|max:11',
           'kcustomdbl1'   => 'required|numeric',
           'kcustomdbl2'   => 'required|numeric',
           'kcustomdbl3'   => 'required|numeric',
           'kcustomdate1'   => 'required|date',
           'kcustomdate2'   => 'required|date',
           'kcustomdate3'   => 'required|date',
           'ksinkron'   => 'required|numeric|max:2',
           'kdownloaded'   => 'required|numeric|max:11',
           'khargacustom'   => 'required|numeric|max:11',
           'kpajakcustom'   => 'required|numeric|max:11',
           'ktotalpiutang'   => 'required|numeric',
           'ktotalhutang'   => 'required|numeric'];
    public $dataPost = 'kid, kkode, knama, kkategori, kkategorinama, kcabang, kcabangnama, klokasi, klokasinama, kgudang, kgudangnama, kkategorisalesman, kkategorisalesmannama, karea, kareanama, kkategoricustomer, kkategoricustomernama, kkategorisupplier, kkategorisuppliernama, kdivisi, kdivisinama, ksubdivisi, ksubdivisinama, ksalesman, ksalesmannama, kkontakperson, kterminglobal, kaktif, kaktiftgl, k1alamat1, k1alamat2, k1alamat3, k1alamat4, k1alamat5, k1kota, k1propinsi, k1kodepos, k1negara, k1kontakperson, k1kontaknohp, k1kontakemail, k1notelp1, k1notelp2, k1nofax, k1email, k1website, k2alamat1, k2alamat2, k2alamat3, k2alamat4, k2alamat5, k2propinsi, k2kota, k2kodepos, k2negara, k2kontakperson, k2kontaknohp, k2kontakemail, k2notelp1, k2notelp2, k2nofax, k2email, k2website, k3alamat1, k3alamat2, k3alamat3, k3alamat4, k3alamat5, k3kota, k3propinsi, k3kodepos, k3negara, k3kontakperson, k3kontaknohp, k3kontakemail, k3notelp1, k3notelp2, k3nofax, k3email, k3website, k4alamat1, k4alamat2, k4alamat3, k4alamat4, k4alamat5, k4kota, k4propinsi, k4kodepos, k4negara, k4kontakperson, k4kontaknohp, k4kontakemail, k4notelp1, k4notelp2, k4nofax, k4email, k4website, knpwp, kpkp, kbatashutang, kterminbeli, krekhutang, kbagpembelian, kfobbeli, kviabeli, kbataspiutang, kterminjual, krekpiutang, kbagpenjualan, ktingkatjual, kfobjual, kviajual, ktglkontrak, kbank, knorekening, kjeniskelamin, kmatauang, ktgllahir, ktglnikah, kkomisikode, kkomisipenjualan, kcatatan, kinputuser, kinputtgl, kcustomtext1, kcustomtext2, kcustomtext3, kcustomtext4, kcustomtext5, kcustomtext6, kcustomtext7, kcustomtext8, kcustomtext9, kcustomtext10, kcustomint1, kcustomint2, kcustomint3, kcustomdbl1, kcustomdbl2, kcustomdbl3, kcustomdate1, kcustomdate2, kcustomdate3, ksinkron, kdownloaded, khargacustom, kpajakcustom, ktotalpiutang, ktotalhutang';

    // Parameter for update data
    public $validatorUpdate = [
           'kkode'   => 'required|max:25',
           'knama'   => 'required|max:100',
           'kkategori'   => 'required|max:20',
           'kkategorinama'   => 'max:50',
           'kcabang'   => 'max:25',
           'kcabangnama'   => 'max:100',
           'klokasi'   => 'max:25',
           'klokasinama'   => 'max:100',
           'kgudang'   => 'max:25',
           'kgudangnama'   => 'max:100',
           'kkategorisalesman'   => 'max:25',
           'kkategorisalesmannama'   => 'max:100',
           'karea'   => 'max:25',
           'kareanama'   => 'max:100',
           'kkategoricustomer'   => 'max:25',
           'kkategoricustomernama'   => 'max:100',
           'kkategorisupplier'   => 'max:25',
           'kkategorisuppliernama'   => 'max:100',
           'kdivisi'   => 'max:25',
           'kdivisinama'   => 'max:100',
           'ksubdivisi'   => 'max:25',
           'ksubdivisinama'   => 'max:100',
           'ksalesman'   => 'numeric|max:20',
           'ksalesmannama'   => 'max:100',
           'kkontakperson'   => 'max:100',
           'kterminglobal'   => 'numeric|max:4',
           'kaktif'   => 'required|numeric|max:2',
           'kaktiftgl'   => 'required|date',
           'k1alamat1'   => 'max:250',
           'k1alamat2'   => 'max:250',
           'k1alamat3'   => 'max:250',
           'k1alamat4'   => 'max:250',
           'k1alamat5'   => 'max:250',
           'k1kota'   => 'max:50',
           'k1propinsi'   => 'max:50',
           'k1kodepos'   => 'max:50',
           'k1negara'   => 'max:50',
           'k1kontakperson'   => 'max:100',
           'k1kontaknohp'   => 'max:50',
           'k1kontakemail'   => 'max:50',
           'k1notelp1'   => 'max:50',
           'k1notelp2'   => 'max:50',
           'k1nofax'   => 'max:50',
           'k1email'   => 'max:50',
           'k1website'   => 'max:50',
           'k2alamat1'   => 'max:250',
           'k2alamat2'   => 'max:250',
           'k2alamat3'   => 'max:250',
           'k2alamat4'   => 'max:250',
           'k2alamat5'   => 'max:250',
           'k2propinsi'   => 'max:50',
           'k2kota'   => 'max:50',
           'k2kodepos'   => 'max:50',
           'k2negara'   => 'max:50',
           'k2kontakperson'   => 'max:100',
           'k2kontaknohp'   => 'max:50',
           'k2kontakemail'   => 'max:50',
           'k2notelp1'   => 'max:50',
           'k2notelp2'   => 'max:50',
           'k2nofax'   => 'max:50',
           'k2email'   => 'max:50',
           'k2website'   => 'max:50',
           'k3alamat1'   => 'max:250',
           'k3alamat2'   => 'max:250',
           'k3alamat3'   => 'max:250',
           'k3alamat4'   => 'max:250',
           'k3alamat5'   => 'max:250',
           'k3kota'   => 'max:50',
           'k3propinsi'   => 'max:50',
           'k3kodepos'   => 'max:50',
           'k3negara'   => 'max:50',
           'k3kontakperson'   => 'max:100',
           'k3kontaknohp'   => 'max:50',
           'k3kontakemail'   => 'max:50',
           'k3notelp1'   => 'max:50',
           'k3notelp2'   => 'max:50',
           'k3nofax'   => 'max:50',
           'k3email'   => 'max:50',
           'k3website'   => 'max:50',
           'k4alamat1'   => 'max:250',
           'k4alamat2'   => 'max:250',
           'k4alamat3'   => 'max:250',
           'k4alamat4'   => 'max:250',
           'k4alamat5'   => 'max:250',
           'k4kota'   => 'max:50',
           'k4propinsi'   => 'max:50',
           'k4kodepos'   => 'max:50',
           'k4negara'   => 'max:50',
           'k4kontakperson'   => 'max:100',
           'k4kontaknohp'   => 'max:50',
           'k4kontakemail'   => 'max:50',
           'k4notelp1'   => 'max:50',
           'k4notelp2'   => 'max:50',
           'k4nofax'   => 'max:50',
           'k4email'   => 'max:50',
           'k4website'   => 'max:50',
           'knpwp'   => 'max:50',
           'kpkp'   => 'numeric|max:2 unsigned',
           'kbatashutang'   => 'numeric',
           'kterminbeli'   => 'max:25',
           'krekhutang'   => 'max:25',
           'kbagpembelian'   => 'numeric|max:20',
           'kfobbeli'   => 'max:25',
           'kviabeli'   => 'max:25',
           'kbataspiutang'   => 'numeric',
           'kterminjual'   => 'max:25',
           'krekpiutang'   => 'max:25',
           'kbagpenjualan'   => 'numeric|max:20 unsigned',
           'ktingkatjual'   => 'numeric|max:11 unsigned',
           'kfobjual'   => 'max:25',
           'kviajual'   => 'max:25',
           'ktglkontrak'   => 'date',
           'kbank'   => 'max:250',
           'knorekening'   => 'max:250',
           'kjeniskelamin'   => 'numeric|max:2 unsigned',
           'kmatauang'   => 'max:10',
           'ktgllahir'   => 'date',
           'ktglnikah'   => 'date',
           'kkomisikode'   => 'max:25',
           'kkomisipenjualan'   => 'numeric',
           'kcatatan'   => 'max:255',
           'kmodifikasiuser'   => 'required|numeric|max:20 unsigned',
           'kmodifikasitgl'   => 'required|date',
           'kcustomtext1'   => 'max:250',
           'kcustomtext2'   => 'max:250',
           'kcustomtext3'   => 'max:250',
           'kcustomtext4'   => 'max:250',
           'kcustomtext5'   => 'max:250',
           'kcustomtext6'   => 'max:250',
           'kcustomtext7'   => 'max:250',
           'kcustomtext8'   => 'max:250',
           'kcustomtext9'   => 'max:250',
           'kcustomtext10'   => 'max:250',
           'kcustomint1'   => 'required|numeric|max:11',
           'kcustomint2'   => 'required|numeric|max:11',
           'kcustomint3'   => 'required|numeric|max:11',
           'kcustomdbl1'   => 'required|numeric',
           'kcustomdbl2'   => 'required|numeric',
           'kcustomdbl3'   => 'required|numeric',
           'kcustomdate1'   => 'required|date',
           'kcustomdate2'   => 'required|date',
           'kcustomdate3'   => 'required|date',
           'ksinkron'   => 'required|numeric|max:2',
           'kdownloaded'   => 'required|numeric|max:11',
           'khargacustom'   => 'required|numeric|max:11',
           'kpajakcustom'   => 'required|numeric|max:11',
           'ktotalpiutang'   => 'required|numeric',
           'ktotalhutang'   => 'required|numeric'];
    public $dataUpdate = 'kkode, knama, kkategori, kkategorinama, kcabang, kcabangnama, klokasi, klokasinama, kgudang, kgudangnama, kkategorisalesman, kkategorisalesmannama, karea, kareanama, kkategoricustomer, kkategoricustomernama, kkategorisupplier, kkategorisuppliernama, kdivisi, kdivisinama, ksubdivisi, ksubdivisinama, ksalesman, ksalesmannama, kkontakperson, kterminglobal, kaktif, kaktiftgl, k1alamat1, k1alamat2, k1alamat3, k1alamat4, k1alamat5, k1kota, k1propinsi, k1kodepos, k1negara, k1kontakperson, k1kontaknohp, k1kontakemail, k1notelp1, k1notelp2, k1nofax, k1email, k1website, k2alamat1, k2alamat2, k2alamat3, k2alamat4, k2alamat5, k2propinsi, k2kota, k2kodepos, k2negara, k2kontakperson, k2kontaknohp, k2kontakemail, k2notelp1, k2notelp2, k2nofax, k2email, k2website, k3alamat1, k3alamat2, k3alamat3, k3alamat4, k3alamat5, k3kota, k3propinsi, k3kodepos, k3negara, k3kontakperson, k3kontaknohp, k3kontakemail, k3notelp1, k3notelp2, k3nofax, k3email, k3website, k4alamat1, k4alamat2, k4alamat3, k4alamat4, k4alamat5, k4kota, k4propinsi, k4kodepos, k4negara, k4kontakperson, k4kontaknohp, k4kontakemail, k4notelp1, k4notelp2, k4nofax, k4email, k4website, knpwp, kpkp, kbatashutang, kterminbeli, krekhutang, kbagpembelian, kfobbeli, kviabeli, kbataspiutang, kterminjual, krekpiutang, kbagpenjualan, ktingkatjual, kfobjual, kviajual, ktglkontrak, kbank, knorekening, kjeniskelamin, kmatauang, ktgllahir, ktglnikah, kkomisikode, kkomisipenjualan, kcatatan, kmodifikasiuser, kmodifikasitgl, kcustomtext1, kcustomtext2, kcustomtext3, kcustomtext4, kcustomtext5, kcustomtext6, kcustomtext7, kcustomtext8, kcustomtext9, kcustomtext10, kcustomint1, kcustomint2, kcustomint3, kcustomdbl1, kcustomdbl2, kcustomdbl3, kcustomdate1, kcustomdate2, kcustomdate3, ksinkron, kdownloaded, khargacustom, kpajakcustom, ktotalpiutang, ktotalhutang';

    // Master 
    public $master = ''; 
    
    public function __construct() 
    {
        $this->master = new MasterController();
        $this->master->tableName        = $this->tableName;
        $this->master->primaryKey       = $this->primaryKey;
        $this->master->select           = $this->select;
        $this->master->selectFormatDate = $this->selectFormatDate;
        $this->master->validatorPost    = $this->validatorPost;
        $this->master->dataPost         = $this->dataPost;
        $this->master->validatorUpdate  = $this->validatorUpdate;
        $this->master->dataUpdate       = $this->dataUpdate;
    }

    public function show(Request $req, Route $route)
    {
        return $this->master->show($req, $route);
    }
    
    public function showById(Request $req, Route $route)
    {
        return $this->master->showById($req, $route);
    }
    
    public function insert(Request $req, Route $route)
    {
        return $this->master->insert($req, $route);
    }
    
    public function update(Request $req, Route $route)
    {
        return $this->master->update($req, $route);
    }
    
    public function delete(Request $req, Route $route)
    {
        return $this->master->delete($req, $route);
    }

}
